-- -- ROLES
-- INSERT INTO role (role_id, name) VALUES (gen_random_uuid(), 'Admin');
-- INSERT INTO role (role_id, name) VALUES (gen_random_uuid(), 'User');

-- -- PLATFORMS
-- INSERT INTO platform (platform_id, name) VALUES (gen_random_uuid(), 'PC');
-- INSERT INTO platform (platform_id, name) VALUES (gen_random_uuid(), 'PlayStation');
-- INSERT INTO platform (platform_id, name) VALUES (gen_random_uuid(), 'Xbox');
-- INSERT INTO platform (platform_id, name) VALUES (gen_random_uuid(), 'Nintendo Switch');
-- INSERT INTO platform (platform_id, name) VALUES (gen_random_uuid(), 'Móvil');

-- -- GENRES
-- INSERT INTO genre (genre_id, name) VALUES (gen_random_uuid(), 'Acción');
-- INSERT INTO genre (genre_id, name) VALUES (gen_random_uuid(), 'Aventura');
-- INSERT INTO genre (genre_id, name) VALUES (gen_random_uuid(), 'Carrera');
-- INSERT INTO genre (genre_id, name) VALUES (gen_random_uuid(), 'RPG');
-- INSERT INTO genre (genre_id, name) VALUES (gen_random_uuid(), 'Simulación');

-- -- GAMES
-- INSERT INTO game (game_id, title, price, description, image, release_date, number_of_sales, stock, total_score, discount, discounted_price) VALUES
--     (gen_random_uuid(), 'The Legend of Zelda: Breath of the Wild', 59.99, 'Explora el vasto reino de Hyrule en esta aventura de mundo abierto.', 'TheLegendOfZeldaBreathOfTheWild.jpg', '2017-03-03', 15000000, 3000, 9.5, 0.10, 53.99);
-- INSERT INTO game (game_id, title, price, description, image, release_date, number_of_sales, stock, total_score, discount, discounted_price) VALUES
--     (gen_random_uuid(), 'The Witcher 3: Wild Hunt', 39.99, 'Embárcate en una búsqueda como Geralt de Rivia en este épico RPG.', 'TheWitcher3WildHunt.jpg', '2015-05-19', 10000000, 3000, 9.8, 0.20, 31.99);
-- INSERT INTO game (game_id, title, price, description, image, release_date, number_of_sales, stock, total_score, discount, discounted_price) VALUES
--     (gen_random_uuid(), 'Red Dead Redemption 2', 49.99, 'Vive la vida de un forajido en el Salvaje Oeste americano.', 'RedDeadRedemption2.jpg', '2018-10-26', 11000000, 3000, 9.7, 0.15, 42.49);
-- INSERT INTO game (game_id, title, price, description, image, release_date, number_of_sales, stock, total_score, discount, discounted_price) VALUES
--     (gen_random_uuid(), 'Grand Theft Auto V', 29.99, 'Experimenta el inframundo criminal en el estado ficticio de San Andreas.', 'GrandTheftAutoV.jpg', '2013-09-17', 140000000, 3000, 9.6, 0.05, 28.49);
-- INSERT INTO game (game_id, title, price, description, image, release_date, number_of_sales, stock, total_score, discount, discounted_price) VALUES
--     (gen_random_uuid(), 'The Elder Scrolls V: Skyrim', 19.99, 'Descubre los misterios de Skyrim en este RPG de mundo abierto.', 'TheElderScrollsVSkyrim.jpg', '2011-11-11', 30000000, 3000, 9.3, 0.25, 14.99);
-- INSERT INTO game (game_id, title, price, description, image, release_date, number_of_sales, stock, total_score, discount, discounted_price) VALUES
--     (gen_random_uuid(), 'Minecraft', 19.99, 'Construye, explora y sobrevive en un mundo abierto hecho de bloques.', 'Minecraft.jpg', '2011-11-18', 200000000, 3000, 9.0, 0.00, 19.99);
-- INSERT INTO game (game_id, title, price, description, image, release_date, number_of_sales, stock, total_score, discount, discounted_price) VALUES
--     (gen_random_uuid(), 'Fortnite', 0.00, 'Lucha contra otros jugadores en esta sensación de battle royale.', 'Fortnite.jpg', '2017-07-25', 350000000, 3000, 8.6, 0.00, 0.00);
-- INSERT INTO game (game_id, title, price, description, image, release_date, number_of_sales, stock, total_score, discount, discounted_price) VALUES
--     (gen_random_uuid(), 'Among Us', 4.99, 'Descubre quienes son los impostores en este juego multijugador de engano.', 'AmongUs.jpg', '2018-11-16', 30000000, 3000, 8.4, 0.30, 3.49);
-- INSERT INTO game (game_id, title, price, description, image, release_date, number_of_sales, stock, total_score, discount, discounted_price) VALUES
--     (gen_random_uuid(), 'Cyberpunk 2077', 39.99, 'Entra en un futuro distopico en este RPG lleno de accion.', 'Cyberpunk2077.jpg', '2020-12-10', 13000000, 3000, 7.2, 0.50, 19.99);
-- INSERT INTO game (game_id, title, price, description, image, release_date, number_of_sales, stock, total_score, discount, discounted_price) VALUES
--     (gen_random_uuid(), 'Call of Duty: Warzone', 0.00, 'Participa en batallas intensas en este battle royale gratuito para jugar.', 'CallOfDutyWarzone.jpg', '2020-03-10', 90000000, 3000, 8.0, 0.00, 0.00);

-- -- SOCIALS
-- INSERT INTO social (social_id, steam_url, twitch_url, youtube_url, discord_tag) VALUES
--     (gen_random_uuid(), 'steam/johndoe', 'twitch/johndoe', 'youtube/johndoe', 'JohnDoe#1234');
-- INSERT INTO social (social_id, steam_url, twitch_url, youtube_url, discord_tag) VALUES
--     (gen_random_uuid(), 'steam/alice', 'twitch/alice', 'youtube/alice', 'Alice#5678');
-- INSERT INTO social (social_id, steam_url, twitch_url, youtube_url, discord_tag) VALUES
--     (gen_random_uuid(), 'steam/bob', 'twitch/bob', 'youtube/bob', 'Bob#9876');
-- INSERT INTO social (social_id, steam_url, twitch_url, youtube_url, discord_tag) VALUES
--     (gen_random_uuid(), 'steam/charlie', 'twitch/charlie', 'youtube/charlie', 'Charlie#6789');
-- INSERT INTO social (social_id, steam_url, twitch_url, youtube_url, discord_tag) VALUES
--     (gen_random_uuid(), 'steam/david', 'twitch/david', 'youtube/david', 'David#5432');

-- -- USERS
-- INSERT INTO users (user_id, email, first_name, last_name, password, phone, profile_pic, username, address_id, role_id, social_id) VALUES
--     (gen_random_uuid(), 'admin@admin.com', 'John', 'Doe', 'adminpass', 672345643, 'john_doe.jpg', 'john_doe', (SELECT address_id FROM address WHERE street_address = 'Calle fake 1'), (SELECT role_id FROM role WHERE name = 'Admin'), (SELECT social_id FROM social WHERE discord_tag = 'JohnDoe#1234'));
-- INSERT INTO users (user_id, email, first_name, last_name, password, phone, profile_pic, username, address_id, role_id, social_id) VALUES
--     (gen_random_uuid(), 'alice@email.com', 'Alice', 'Wonder', 'hashed_password', 679124543, 'alice.jpg', 'alice_wonder', (SELECT address_id FROM address WHERE street_address = 'Calle fake 2'), (SELECT role_id FROM role WHERE name = 'User'), (SELECT social_id FROM social WHERE discord_tag = 'Alice#5678'));
-- INSERT INTO users (user_id, email, first_name, last_name, password, phone, profile_pic, username, address_id, role_id, social_id) VALUES
--     (gen_random_uuid(), 'bob@email.com', 'Bob', 'Aventurar', 'hashed_password', 680687233, 'bob.jpg', 'bob_Aventurar', (SELECT address_id FROM address WHERE street_address = 'Calle fake 3'), (SELECT role_id FROM role WHERE name = 'User'), (SELECT social_id FROM social WHERE discord_tag = 'Bob#9876'));
-- INSERT INTO users (user_id, email, first_name, last_name, password, phone, profile_pic, username, address_id, role_id, social_id) VALUES
--     (gen_random_uuid(), 'charlie@email.com', 'Charlie', 'Gamer', 'hashed_password', 679237543, 'charlie.jpg', 'charlie_gamer', (SELECT address_id FROM address WHERE street_address = 'Calle fake 4'), (SELECT role_id FROM role WHERE name = 'User'), (SELECT social_id FROM social WHERE discord_tag = 'Charlie#6789'));
-- INSERT INTO users (user_id, email, first_name, last_name, password, phone, profile_pic, username, address_id, role_id, social_id) VALUES
--     (gen_random_uuid(), 'david@email.com', 'David', 'Player', 'hashed_password', 679687543, 'david.jpg', 'david_player', (SELECT address_id FROM address WHERE street_address = 'Calle fake 5'), (SELECT role_id FROM role WHERE name = 'User'), (SELECT social_id FROM social WHERE discord_tag = 'David#5432'));
-- INSERT INTO users (user_id, email, first_name, last_name, password, phone, profile_pic, username, address_id, role_id, social_id) VALUES
--     (gen_random_uuid(), 'eliza@email.com', 'Eliza', 'Gamer', 'hashed_password', 739682243, 'eliza.jpg', 'eliza_gamer', (SELECT address_id FROM address WHERE street_address = 'Calle fake 6'), (SELECT role_id FROM role WHERE name = 'User'), null);

-- -- GAME PLATFORM RELATIONSHIP
-- INSERT INTO game_platform (platform_id, game_id) VALUES
--     ((SELECT platform_id FROM platform WHERE name = 'PC'), (SELECT game_id FROM game WHERE title = 'The Legend of Zelda: Breath of the Wild'));
-- INSERT INTO game_platform (platform_id, game_id) VALUES
--     ((SELECT platform_id FROM platform WHERE name = 'PlayStation'), (SELECT game_id FROM game WHERE title = 'The Witcher 3: Wild Hunt'));
-- INSERT INTO game_platform (platform_id, game_id) VALUES
--     ((SELECT platform_id FROM platform WHERE name = 'Xbox'), (SELECT game_id FROM game WHERE title = 'Red Dead Redemption 2'));
-- INSERT INTO game_platform (platform_id, game_id) VALUES
--     ((SELECT platform_id FROM platform WHERE name = 'Nintendo Switch'), (SELECT game_id FROM game WHERE title = 'The Legend of Zelda: Breath of the Wild'));
-- INSERT INTO game_platform (platform_id, game_id) VALUES
--     ((SELECT platform_id FROM platform WHERE name = 'Móvil'), (SELECT game_id FROM game WHERE title = 'Fortnite'));

-- -- GAME GENRE RELATIONSHIP
-- INSERT INTO game_genre (game_id, genre_id) VALUES
--     ((SELECT game_id FROM game WHERE title = 'The Legend of Zelda: Breath of the Wild'), (SELECT genre_id FROM genre WHERE name = 'Acción'));
-- INSERT INTO game_genre (game_id, genre_id) VALUES
--     ((SELECT game_id FROM game WHERE title = 'The Witcher 3: Wild Hunt'), (SELECT genre_id FROM genre WHERE name = 'RPG'));
-- INSERT INTO game_genre (game_id, genre_id) VALUES
--     ((SELECT game_id FROM game WHERE title = 'Red Dead Redemption 2'), (SELECT genre_id FROM genre WHERE name = 'Acción'));
-- INSERT INTO game_genre (game_id, genre_id) VALUES
--     ((SELECT game_id FROM game WHERE title = 'Grand Theft Auto V'), (SELECT genre_id FROM genre WHERE name = 'RPG'));
-- INSERT INTO game_genre (game_id, genre_id) VALUES
--     ((SELECT game_id FROM game WHERE title = 'Minecraft'), (SELECT genre_id FROM genre WHERE name = 'Simulación'));

-- -- REVIEWS
-- INSERT INTO review (review_id, user_id, game_id, score, comment) VALUES
--     (gen_random_uuid(), (SELECT user_id FROM users WHERE username = 'john_doe'), (SELECT game_id FROM game WHERE title = 'The Legend of Zelda: Breath of the Wild'), 4.5, 'Exciting Aventura!');
-- INSERT INTO review (review_id, user_id, game_id, score, comment) VALUES
--     (gen_random_uuid(), (SELECT user_id FROM users WHERE username = 'alice_wonder'), (SELECT game_id FROM game WHERE title = 'The Witcher 3: Wild Hunt'), 4.2, 'Great RPG game!');
-- INSERT INTO review (review_id, user_id, game_id, score, comment) VALUES
--     (gen_random_uuid(), (SELECT user_id FROM users WHERE username = 'bob_Aventurar'), (SELECT game_id FROM game WHERE title = 'Red Dead Redemption 2'), 4.8, 'Amazing open world!');
-- INSERT INTO review (review_id, user_id, game_id, score, comment) VALUES
--     (gen_random_uuid(), (SELECT user_id FROM users WHERE username = 'charlie_gamer'), (SELECT game_id FROM game WHERE title = 'Grand Theft Auto V'), 3.9, 'Crime-filled Aventura!');
-- INSERT INTO review (review_id, user_id, game_id, score, comment) VALUES
--     (gen_random_uuid(), (SELECT user_id FROM users WHERE username = 'david_player'), (SELECT game_id FROM game WHERE title = 'Minecraft'), 4.1, 'Endless creativity!');

-- -- PROVIDERS
-- INSERT INTO provider (provider_id, name, address, phone, email) VALUES
--     (gen_random_uuid(), 'GameCo', '123 Game St, Gametown', '123-456-7890', 'contact@gameco.com');
-- INSERT INTO provider (provider_id, name, address, phone, email) VALUES
--     (gen_random_uuid(), 'Aventura Games', '456 Quest Ave, Aventura City', '987-654-3210', 'info@Aventuragames.com');
-- INSERT INTO provider (provider_id, name, address, phone, email) VALUES
--     (gen_random_uuid(), 'Space Explorers', '789 Universe Rd, Space Center', '111-222-3333', 'support@spaceexplorers.com');

-- -- ACCOUNTS
-- INSERT INTO account (account_id, provider_id, account_holder_name, account_number, bank_name, bank_address, bank_routing_number, account_balance) VALUES
--     (gen_random_uuid(), (SELECT provider_id FROM provider WHERE name = 'GameCo'), 'GameCo Account Holder', '12345678', 'Game Bank', '123 Bank St', '98765432', 1000000.00);
-- INSERT INTO account (account_id, provider_id, account_holder_name, account_number, bank_name, bank_address, bank_routing_number, account_balance) VALUES
--     (gen_random_uuid(), (SELECT provider_id FROM provider WHERE name = 'Aventura Games'), 'Aventura Games Account Holder', '87654321', 'Aventura Bank', '456 Aventura Ave', '12345678', 750000.00);
-- INSERT INTO account (account_id, provider_id, account_holder_name, account_number, bank_name, bank_address, bank_routing_number, account_balance) VALUES
--     (gen_random_uuid(), (SELECT provider_id FROM provider WHERE name = 'Space Explorers'), 'Space Explorers Account Holder', '1111222233334444', 'Space Bank', '789 Space Rd', '55556666', 500000.00);

-- -- PURCHASES
-- INSERT INTO purchase (purchase_id, provider_id, purchase_date, total_amount) VALUES
--     (gen_random_uuid(), (SELECT provider_id FROM provider WHERE name = 'GameCo'), '2023-08-07', 299.99);
-- INSERT INTO purchase (purchase_id, provider_id, purchase_date, total_amount) VALUES
--     (gen_random_uuid(), (SELECT provider_id FROM provider WHERE name = 'Aventura Games'), '2023-08-08', 199.99);
-- INSERT INTO purchase (purchase_id, provider_id, purchase_date, total_amount) VALUES
--     (gen_random_uuid(), (SELECT provider_id FROM provider WHERE name = 'Space Explorers'), '2023-08-09', 399.99);

-- -- PURCHASE DETAILS
-- INSERT INTO purchase_detail (purchase_detail_id, purchase_id, game_id, quantity, subtotal) VALUES
--     (gen_random_uuid(), (SELECT purchase_id FROM purchase WHERE purchase_date = '2023-08-07'), (SELECT game_id FROM game WHERE title = 'The Legend of Zelda: Breath of the Wild'), 1, 59.99);
-- INSERT INTO purchase_detail (purchase_detail_id, purchase_id, game_id, quantity, subtotal) VALUES
--     (gen_random_uuid(), (SELECT purchase_id FROM purchase WHERE purchase_date = '2023-08-08'), (SELECT game_id FROM game WHERE title = 'The Witcher 3: Wild Hunt'), 1, 39.99);
-- INSERT INTO purchase_detail (purchase_detail_id, purchase_id, game_id, quantity, subtotal) VALUES
--     (gen_random_uuid(), (SELECT purchase_id FROM purchase WHERE purchase_date = '2023-08-09'), (SELECT game_id FROM game WHERE title = 'Red Dead Redemption 2'), 1, 49.99);

-- -- SALES
-- INSERT INTO sale (sale_id, user_id, sale_date, total_amount) VALUES
--     (gen_random_uuid(), (SELECT user_id FROM users WHERE username = 'john_doe'), '2023-08-10', 59.99);
-- INSERT INTO sale (sale_id, user_id, sale_date, total_amount) VALUES
--     (gen_random_uuid(), (SELECT user_id FROM users WHERE username = 'alice_wonder'), '2023-08-11', 49.99);
-- INSERT INTO sale (sale_id, user_id, sale_date, total_amount) VALUES
--     (gen_random_uuid(), (SELECT user_id FROM users WHERE username = 'bob_Aventurar'), '2023-08-12', 69.99);

-- -- SALE DETAILS
-- INSERT INTO sale_detail (sale_detail_id, sale_id, game_id, quantity, subtotal) VALUES
--     (gen_random_uuid(), (SELECT sale_id FROM sale WHERE sale_date = '2023-08-10'), (SELECT game_id FROM game WHERE title = 'The Legend of Zelda: Breath of the Wild'), 1, 59.99);
-- INSERT INTO sale_detail (sale_detail_id, sale_id, game_id, quantity, subtotal) VALUES
--     (gen_random_uuid(), (SELECT sale_id FROM sale WHERE sale_date = '2023-08-11'), (SELECT game_id FROM game WHERE title = 'The Witcher 3: Wild Hunt'), 1, 39.99);
-- INSERT INTO sale_detail (sale_detail_id, sale_id, game_id, quantity, subtotal) VALUES
--     (gen_random_uuid(), (SELECT sale_id FROM sale WHERE sale_date = '2023-08-12'), (SELECT game_id FROM game WHERE title = 'Red Dead Redemption 2'), 1, 49.99);
